spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quantum_service_faas_db?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    host: localhost
    port: 1414
    user: admin
    password: passw0rd

messaging:
  enabled: true
  eventQueue: DEV.QUEUE.1
