spring:
  datasource:
    url: jdbc:db2://${IBM_DB2_HOST}:${IBM_DB2_PORT}/${IBM_DB2_DATABASE}
    username: ${IBM_DB2_USERNAME}
    password: ${IBM_DB2_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

ibm:
  mq:
    queueManager: ${IBM_MQ_QUEUE_MANAGER}
    channel: ${IBM_MQ_QUEUE_CHANNEL}
    connName: ${IBM_MQ_QUEUE_CONNECTION_ADDRESS}
    user: ${IBM_MQ_QUEUE_USERNAME}
    password: ${IBM_MQ_QUEUE_PASSWORD}
